[project]
name = "drink-reminder"
version = "0.1.0"
description = "Track your drinking foo'!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "nicegui>=2.21.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
